"atom":
  "object":
    "robot": ~
    "node": ~
    "highway": ~
    "shelf": ~
    "pickingStation": ~
    "order": ~
    "product": ~
  "value":
    - "coord":
  "action":
    - "move"
    - "pickup"
    - "putdown"
    - "deliver"

"background_color": "black"

"categories":
  "init": "<RE>"
  "occurs": "<RE>"
