"atom":
  "object":

    "item": #Visually depicted objects
      "node": "sprites/asprilo/node.svg"
      "highway": "sprites/asprilo/highway.svg"
      "robot": "sprites/asprilo/robot.svg"
      "shelf": "sprites/asprilo/shelf.svg"
      "pickingStation": "sprites/asprilo/pickingStation.svg"
    
    "abstract": #Objects which are not visually depicted
      "order": ~ #Maybe use empty space for further specification?
      "product": ~

  "value":
    - "coord":

  "action": #Somehow alias equivalent function
    "move": "move"
    "pickup": "pick_up"
    "putdown": "put_down"
    "deliver": "satisfy"

"background_color": "black"
